#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "wikitext.h"
#include "monsym_table.h"

/* ---------------- small dynamic string buffer ---------------- */

typedef struct { char *buf; size_t len, cap; } SB;

static void sb_init(SB *s) { s->cap = 256; s->len = 0; s->buf = malloc(s->cap); s->buf[0] = '\0'; }
static void sb_ensure(SB *s, size_t extra) {
    if (s->len + extra + 1 > s->cap) {
        while (s->len + extra + 1 > s->cap) s->cap *= 2;
        s->buf = realloc(s->buf, s->cap);
    }
}
static void sb_putc(SB *s, char c) { sb_ensure(s, 1); s->buf[s->len++] = c; s->buf[s->len] = '\0'; }
static void sb_puts(SB *s, const char *str) {
    size_t n = strlen(str);
    sb_ensure(s, n);
    memcpy(s->buf + s->len, str, n);
    s->len += n;
    s->buf[s->len] = '\0';
}

static void trim_inplace(char *s) {
    size_t n = strlen(s);
    size_t start = 0;
    while (start < n && isspace((unsigned char)s[start])) start++;
    size_t end = n;
    while (end > start && isspace((unsigned char)s[end - 1])) end--;
    size_t len = end - start;
    memmove(s, s + start, len);
    s[len] = '\0';
}

static int starts_with(const char *s, const char *prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}
static int starts_with_ci(const char *s, const char *prefix) {
    return strncasecmp(s, prefix, strlen(prefix)) == 0;
}
static char *find_ci(const char *hay, const char *needle) {
    size_t nn = strlen(needle);
    for (const char *p = hay; *p; p++) {
        if (strncasecmp(p, needle, nn) == 0) return (char *)p;
    }
    return NULL;
}

/* ---------------- preprocessing passes ----------------
 * Each pass consumes its input string (frees it) and returns a freshly
 * allocated result. Order matters: structural markup (comments, templates,
 * refs, tags) is stripped before HTML entities are decoded, so an editor
 * writing "&lt;ref&gt;" to show literal text isn't later mis-parsed as a
 * real tag. */

static char *strip_comments(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with(p, "<!--")) {
            char *end = strstr(p + 4, "-->");
            p = end ? end + 3 : p + strlen(p);
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

/* Most templates carry layout/citation plumbing we can't reproduce without
 * a real MediaWiki engine, so they're dropped. A handful of very common
 * ones are meaningful *inline text* wrapped in template syntax -- notably
 * the {{colorname|X}} templates NetHackWiki uses to color dungeon-symbol
 * glyphs (used constantly in ASCII maps and legends). Deleting those
 * wholesale was erasing the glyph itself, not just its color, so they're
 * unwrapped to their argument instead. */
typedef enum { TPL_DROP, TPL_LAST_ARG, TPL_FIRST_ARG, TPL_FRAC, TPL_PIPE, TPL_OF_LIST,
               TPL_MONSYM, TPL_MONSYMLINK } TplAction;

/* {{monsym|name}} / {{monsymlink|name}} mark up a monster's single-character
 * dungeon map glyph -- e.g. {{monsym|monkey}} is the 'Y' a monkey appears as
 * on screen, not the word "monkey". That distinction matters a lot more here
 * than for the {{colorname|X}} templates above: those already wrap a literal
 * glyph character (color is discarded, same as elsewhere in this parser),
 * but {{monsym|X}} only takes the monster's *name*, so producing the glyph
 * means looking it up. On an ASCII map, printing the wrong thing here -- the
 * previous behavior just emitted the monster's name -- silently turns a
 * single grid cell into a multi-character string and wrecks every column
 * after it (see apply_replacecharsblock()). monsym_table.h is generated by
 * scripts/04_gen_monsym_table.py from vanilla NetHack's own monster list
 * (include/monsters.h's class per monster, mapped through include/defsym.h's
 * class-to-character table), so it can't drift from what the game itself
 * draws. `monsymlink` additionally emits [[name|glyph]] wikilink syntax --
 * not a resolved link, just the source text for one -- so it flows through
 * the normal [[...]] handling in inline_parse() same as any hand-written
 * wikilink; this raw-text preprocessing stage runs before the Doc/RunList
 * structures inline_parse() resolves links into even exist, so producing
 * an already-resolved link here isn't an option regardless of what
 * strip_templates() itself has access to. */
static char monsym_lookup(const char *raw_name) {
    char buf[128];
    size_t j = 0;
    for (const char *p = raw_name; *p && j < sizeof(buf) - 1; p++)
        buf[j++] = (*p == '_') ? ' ' : *p;
    buf[j] = '\0';
    trim_inplace(buf);

    for (int i = 0; i < MONSYM_TABLE_LEN; i++)
        if (strcasecmp(buf, monsym_table[i].name) == 0) return monsym_table[i].ch;

    /* Strip a trailing " (disambiguator)" qualifier -- e.g. wiki prose uses
     * {{monsymlink|acolyte (quest guardian)}} to link a specific mention,
     * but the monster is just "acolyte" in NetHack's own monster list --
     * and retry once. */
    char *paren = strrchr(buf, '(');
    if (paren && paren > buf) {
        *paren = '\0';
        trim_inplace(buf);
        for (int i = 0; i < MONSYM_TABLE_LEN; i++)
            if (strcasecmp(buf, monsym_table[i].name) == 0) return monsym_table[i].ch;
    }

    return '\0'; /* not found -- caller falls back to '?', NetHack's own
                  * "unidentified thing" glyph, rather than corrupting a
                  * map's column alignment with unresolved text. Expected
                  * for monsters that exist only in a variant (SLASH'EM,
                  * dNetHack, ...) this table has no data for. */
}

/* NetHackWiki price/spoiler tables lean heavily on a family of templates
 * shaped like {{scroll of|a|b|c}}, {{wand of|a|or=1|b}}, or the generic
 * {{of|noun|a|b}} -- each expands to "<noun> of <item list>", optionally
 * joined with "and"/"or" before the last item instead of a comma. Every
 * such template name either *is* "of" (noun supplied as args[1]) or *ends*
 * in " of" (the noun is baked into the template name itself, e.g. "wand
 * of"). Recognizing the whole family by that shape -- rather than listing
 * every "X of" template individually -- means new ones (ring of, potion
 * of, spellbook of, ...) work without another entry here. */
static int ends_with_ci(const char *s, const char *suffix) {
    size_t sl = strlen(s), fl = strlen(suffix);
    return sl >= fl && strcasecmp(s + sl - fl, suffix) == 0;
}

static TplAction template_action(const char *name) {
    static const char *color_names[] = {
        "white", "brown", "cyan", "magenta", "red", "lightgray", "green", "yellow", "blue",
        "darkgray", "gray", "grey", "black", "orange", "silver",
        "brightblack", "brightred", "brightgreen", "brightyellow", "brightblue",
        "brightmagenta", "brightcyan", "brightwhite", NULL
    };
    for (int i = 0; color_names[i]; i++) if (strcasecmp(name, color_names[i]) == 0) return TPL_LAST_ARG;
    if (strcasecmp(name, "kbd") == 0) return TPL_LAST_ARG;
    if (strcmp(name, "!") == 0) return TPL_PIPE;
    if (strcasecmp(name, "frac") == 0) return TPL_FRAC;
    if (strcasecmp(name, "message") == 0) return TPL_FIRST_ARG;
    if (strcasecmp(name, "monsym") == 0) return TPL_MONSYM;
    if (strcasecmp(name, "monsymlink") == 0) return TPL_MONSYMLINK;
    if (strcasecmp(name, "of") == 0) return TPL_OF_LIST;
    if (ends_with_ci(name, " of")) return TPL_OF_LIST;
    return TPL_DROP;
}

/* Renders the {{<name> of|item|item|...}} / {{of|noun|item|item|...}}
 * family described above. A `key=value` argument (e.g. "or=1", "and=1",
 * "version=...") is never itself a list item: if the key is "or" or "and"
 * it picks the word used before the final item ("a, b, or c"); any other
 * key is just citation/formatting plumbing and is dropped, same as a
 * template this parser doesn't recognize at all. */
static void emit_of_list(SB *out, char **args, int n) {
    int first_item;
    if (strcasecmp(args[0], "of") == 0) {
        if (n < 3) return;
        sb_puts(out, args[1]);
        sb_puts(out, " of ");
        first_item = 2;
    } else {
        if (n < 2) return;
        sb_puts(out, args[0]);
        sb_putc(out, ' ');
        first_item = 1;
    }

    const char *joiner = NULL;
    char *items[64];
    int nitems = 0;
    for (int i = first_item; i < n && nitems < 64; i++) {
        char *eq = strchr(args[i], '=');
        if (eq) {
            size_t klen = (size_t)(eq - args[i]);
            if (klen == 2 && strncasecmp(args[i], "or", 2) == 0) joiner = " or ";
            else if (klen == 3 && strncasecmp(args[i], "and", 3) == 0) joiner = " and ";
            continue;
        }
        items[nitems++] = args[i];
    }

    for (int i = 0; i < nitems; i++) {
        if (i > 0) sb_puts(out, (joiner && i == nitems - 1) ? joiner : ", ");
        sb_puts(out, items[i]);
    }
}

/* Splits the span between {{ and the matching }} on top-level '|'
 * characters (ignoring '|' inside nested {{ }} or [[ ]]). args[0] is the
 * template name. Returns a malloc'd array of malloc'd, trimmed strings. */
static char **template_split_args(const char *start, const char *end, int *out_n) {
    int cap = 8, n = 0;
    char **out = malloc(cap * sizeof(char *));
    int depth = 0;
    const char *seg = start;
    const char *p = start;
    while (p < end) {
        if (p + 1 < end && ((p[0] == '{' && p[1] == '{') || (p[0] == '[' && p[1] == '['))) { depth++; p += 2; continue; }
        if (p + 1 < end && ((p[0] == '}' && p[1] == '}') || (p[0] == ']' && p[1] == ']'))) { if (depth > 0) depth--; p += 2; continue; }
        if (depth == 0 && *p == '|') {
            size_t len = (size_t)(p - seg);
            char *piece = malloc(len + 1);
            memcpy(piece, seg, len);
            piece[len] = '\0';
            trim_inplace(piece);
            if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
            out[n++] = piece;
            p++;
            seg = p;
            continue;
        }
        p++;
    }
    size_t len = (size_t)(end - seg);
    char *piece = malloc(len + 1);
    memcpy(piece, seg, len);
    piece[len] = '\0';
    trim_inplace(piece);
    if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
    out[n++] = piece;
    *out_n = n;
    return out;
}

static void free_args(char **args, int n) {
    for (int i = 0; i < n; i++) free(args[i]);
    free(args);
}

/* --- transclusion-only tag handling -- used only when splicing a
 * template's own wikitext into a host page below, never for a page's own
 * direct-view rendering (preprocess()'s main pipeline). Real MediaWiki
 * semantics are the mirror image of each other for the two cases:
 * <noinclude> content shows on direct view of the page it's written on
 * but is dropped when that page is transcluded elsewhere; <includeonly>
 * is the opposite. Since every page this app renders is a direct view
 * (nothing else calls wikitext_parse() on a page being viewed "as
 * transcluded"), only the transclusion-side handling -- used here, on a
 * template's content right before splicing it in -- is needed. Confirmed
 * necessary by Template:Weapon skill table, which wraps a "how this page
 * was generated" note and a category link in <noinclude> that would
 * otherwise leak into every article that transcludes it. */
static char *strip_noinclude(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<noinclude")) {
            char *gt = strchr(p, '>');
            if (!gt) { p += strlen(p); break; }
            int self_closing = (gt > p && *(gt - 1) == '/');
            if (self_closing) { p = gt + 1; continue; }
            char *close = find_ci(gt, "</noinclude>");
            p = close ? close + strlen("</noinclude>") : p + strlen(p);
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

static char *unwrap_includeonly(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<includeonly") || starts_with_ci(p, "</includeonly")) {
            char *gt = strchr(p, '>');
            p = gt ? gt + 1 : p + strlen(p);
            continue;
        }
        sb_putc(&out, *p);
        p++;
    }
    free(in);
    return out.buf;
}

/* A template transclusion can only be expanded this many levels deep --
 * cycle protection for a template that transitively includes itself,
 * which would otherwise recurse until the stack overflows. Far more than
 * any legitimate template chain on this wiki actually needs. */
#define TEMPLATE_MAX_DEPTH 8

/* Mirrors scripts/02_extract_pages.py's safe_filename(): the same
 * characters that can appear in a MediaWiki title but not in a filesystem
 * path get replaced with '_' there when writing each pages_templates/ file,
 * so a lookup here has to apply the identical substitution to land on
 * the same filename (e.g. "Template:Weapon skill table" was written as
 * "Template_Weapon skill table.wiki"). */
static void safe_filename_title(const char *title, char *out, size_t outsz) {
    size_t o = 0;
    for (const char *p = title; *p && o + 1 < outsz; p++) {
        char c = *p;
        if (c == '/' || c == '\\' || c == ':' || c == '*' || c == '?' ||
            c == '"' || c == '<' || c == '>' || c == '|') {
            c = '_';
        }
        out[o++] = c;
    }
    out[o] = '\0';
}

static char *strip_templates(char *in, const WikiIndex *idx, int depth);

/* Expands a template transclusion by looking up its own extracted
 * wikitext (idx->templates, populated by `02_extract_pages.py --namespace
 * 10`) and recursively processing it, or returns NULL if there's no such
 * template available locally, or `depth` has already hit
 * TEMPLATE_MAX_DEPTH. This doesn't attempt MediaWiki's {{{1}}} parameter
 * substitution -- callers only try this for a *bare* "{{Name}}"
 * invocation with no arguments, which covers static data templates like
 * the skill tables (their content doesn't vary per invocation) but not
 * genuinely parameterized ones (those still just drop, as before this
 * existed). Result is malloc'd; caller frees it. */
static char *expand_template_for_transclusion(const char *template_name, const WikiIndex *idx, int depth) {
    if (!idx || !idx->templates || depth >= TEMPLATE_MAX_DEPTH) return NULL;

    char full_title[1024];
    snprintf(full_title, sizeof full_title, "Template:%s", template_name);
    for (char *c = full_title; *c; c++) if (*c == '_') *c = ' ';

    char fname[1024];
    safe_filename_title(full_title, fname, sizeof fname);

    int ti = wiki_index_find(idx->templates, fname);
    if (ti < 0) return NULL;

    char *raw = wiki_index_read(idx->templates, ti);
    if (!raw) return NULL;

    char *s = strip_comments(raw);
    s = strip_noinclude(s);
    s = unwrap_includeonly(s);
    s = strip_templates(s, idx, depth + 1);
    return s;
}

static char *strip_templates(char *in, const WikiIndex *idx, int depth) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (p[0] == '{' && p[1] == '{') {
            const char *inner_start = p + 2;
            int brace_depth = 1;
            p += 2;
            while (*p && brace_depth > 0) {
                if (p[0] == '{' && p[1] == '{') { brace_depth++; p += 2; }
                else if (p[0] == '}' && p[1] == '}') { brace_depth--; p += 2; }
                else p++;
            }
            const char *inner_end = (brace_depth == 0) ? p - 2 : p; /* exclude the closing }} */

            int n;
            char **args = template_split_args(inner_start, inner_end, &n);
            TplAction action = template_action(args[0]);
            switch (action) {
            case TPL_LAST_ARG:
                if (n >= 2) sb_puts(&out, args[n - 1]);
                break;
            case TPL_FIRST_ARG:
                if (n >= 2) sb_puts(&out, args[1]);
                break;
            case TPL_FRAC:
                /* {{frac|a|b}} -> "a/b"; the single-arg form {{frac|n}} is
                 * shorthand for a "1 in n" probability, i.e. "1/n". */
                if (n >= 3) { sb_puts(&out, args[1]); sb_putc(&out, '/'); sb_puts(&out, args[2]); }
                else if (n == 2) { sb_puts(&out, "1/"); sb_puts(&out, args[1]); }
                break;
            case TPL_PIPE:
                sb_putc(&out, '|');
                break;
            case TPL_OF_LIST:
                emit_of_list(&out, args, n);
                break;
            case TPL_MONSYM:
                if (n >= 2) {
                    char ch = monsym_lookup(args[1]);
                    sb_putc(&out, ch ? ch : '?');
                }
                break;
            case TPL_MONSYMLINK:
                if (n >= 2) {
                    char ch = monsym_lookup(args[1]);
                    sb_puts(&out, "[[");
                    sb_puts(&out, args[1]);
                    sb_putc(&out, '|');
                    sb_putc(&out, ch ? ch : '?');
                    sb_puts(&out, "]]");
                }
                break;
            case TPL_DROP:
            default:
                /* Not a template this parser knows how to interpret
                 * inline -- but if it's a bare "{{Name}}" (no arguments,
                 * so there's no {{{1}}}-style parameter substitution to
                 * get wrong) and we have that template's own extracted
                 * wikitext available, splice its expansion in instead of
                 * silently dropping it. Genuinely parameterized unknown
                 * templates (n > 1) still just drop, same as before. */
                if (n == 1) {
                    char *expanded = expand_template_for_transclusion(args[0], idx, depth);
                    if (expanded) {
                        sb_puts(&out, expanded);
                        free(expanded);
                    }
                }
                break;
            }
            free_args(args, n);
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

static char *strip_gallery(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<gallery")) {
            char *close = find_ci(p, "</gallery>");
            p = close ? close + strlen("</gallery>") : p + strlen(p);
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

static char *strip_refs(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<ref")) {
            char *gt = strchr(p, '>');
            if (!gt) { p += strlen(p); break; }
            int self_closing = (gt > p && *(gt - 1) == '/');
            if (self_closing) { p = gt + 1; continue; }
            char *close = find_ci(gt, "</ref>");
            p = close ? close + strlen("</ref>") : p + strlen(p);
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

static char *br_to_newline(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<br")) {
            char *gt = strchr(p, '>');
            if (gt) { sb_putc(&out, '\n'); p = gt + 1; continue; }
        }
        sb_putc(&out, *p);
        p++;
    }
    free(in);
    return out.buf;
}

/* Marks each line inside <pre>...</pre> with a sentinel byte so the
 * block-level parser (which runs after tag-stripping has removed the <pre>
 * markers themselves) can still recognize them as preformatted -- same
 * verbatim, non-wrapped treatment as MediaWiki's leading-space convention. */
#define PRE_MARK '\x01'

static char *mark_pre_blocks(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<pre")) {
            char *gt = strchr(p, '>');
            if (!gt) { p += strlen(p); break; }
            int self_closing = (gt > p && *(gt - 1) == '/');
            p = gt + 1;
            if (self_closing) continue;
            char *close = find_ci(p, "</pre>");
            char *end = close ? close : p + strlen(p);
            sb_putc(&out, PRE_MARK);
            for (char *q = p; q < end; q++) {
                sb_putc(&out, *q);
                if (*q == '\n') sb_putc(&out, PRE_MARK);
            }
            p = close ? close + strlen("</pre>") : end;
        } else {
            sb_putc(&out, *p);
            p++;
        }
    }
    free(in);
    return out.buf;
}

static char *strip_nowiki_markers(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (starts_with_ci(p, "<nowiki") || starts_with_ci(p, "</nowiki")) {
            char *gt = strchr(p, '>');
            p = gt ? gt + 1 : p + strlen(p);
            continue;
        }
        sb_putc(&out, *p);
        p++;
    }
    free(in);
    return out.buf;
}

static char *strip_generic_tags(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (*p == '<' && (p[1] == '/' || isalpha((unsigned char)p[1]))) {
            char *gt = strchr(p, '>');
            if (gt) { p = gt + 1; continue; }
        }
        sb_putc(&out, *p);
        p++;
    }
    free(in);
    return out.buf;
}

/* Encodes a Unicode code point as UTF-8 (the locale ui.c sets up via
 * setlocale(LC_ALL, "") in main.c, so ncursesw can display it directly). */
static void sb_put_utf8(SB *s, long code) {
    if (code < 0 || code > 0x10FFFF) { sb_putc(s, '?'); return; }
    if (code < 0x80) {
        sb_putc(s, (char)code);
    } else if (code < 0x800) {
        sb_putc(s, (char)(0xC0 | (code >> 6)));
        sb_putc(s, (char)(0x80 | (code & 0x3F)));
    } else if (code < 0x10000) {
        sb_putc(s, (char)(0xE0 | (code >> 12)));
        sb_putc(s, (char)(0x80 | ((code >> 6) & 0x3F)));
        sb_putc(s, (char)(0x80 | (code & 0x3F)));
    } else {
        sb_putc(s, (char)(0xF0 | (code >> 18)));
        sb_putc(s, (char)(0x80 | ((code >> 12) & 0x3F)));
        sb_putc(s, (char)(0x80 | ((code >> 6) & 0x3F)));
        sb_putc(s, (char)(0x80 | (code & 0x3F)));
    }
}

static char *decode_entities(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (*p == '&') {
            if (starts_with(p, "&amp;")) { sb_putc(&out, '&'); p += 5; continue; }
            if (starts_with(p, "&lt;")) { sb_putc(&out, '<'); p += 4; continue; }
            if (starts_with(p, "&gt;")) { sb_putc(&out, '>'); p += 4; continue; }
            if (starts_with(p, "&quot;")) { sb_putc(&out, '"'); p += 6; continue; }
            if (starts_with(p, "&apos;")) { sb_putc(&out, '\''); p += 6; continue; }
            if (starts_with(p, "&nbsp;")) { sb_putc(&out, ' '); p += 6; continue; }
            if (starts_with(p, "&mdash;")) { sb_puts(&out, "--"); p += 7; continue; }
            if (starts_with(p, "&ndash;")) { sb_puts(&out, "-"); p += 7; continue; }
            if (starts_with(p, "&hellip;")) { sb_puts(&out, "..."); p += 8; continue; }
            if (starts_with(p, "&minus;")) { sb_putc(&out, '-'); p += 7; continue; }
            if (starts_with(p, "&shy;")) { p += 5; continue; } /* soft hyphen: invisible */
            if (starts_with(p, "&le;")) { sb_put_utf8(&out, 0x2264); p += 4; continue; }
            if (starts_with(p, "&ge;")) { sb_put_utf8(&out, 0x2265); p += 4; continue; }
            if (starts_with(p, "&times;")) { sb_put_utf8(&out, 0x00D7); p += 7; continue; }
            if (starts_with(p, "&divide;")) { sb_put_utf8(&out, 0x00F7); p += 8; continue; }
            if (starts_with(p, "&plusmn;")) { sb_put_utf8(&out, 0x00B1); p += 8; continue; }
            if (starts_with(p, "&deg;")) { sb_put_utf8(&out, 0x00B0); p += 5; continue; }
            if (starts_with(p, "&rarr;")) { sb_put_utf8(&out, 0x2192); p += 6; continue; }
            if (starts_with(p, "&para;")) { sb_put_utf8(&out, 0x00B6); p += 6; continue; }
            if (starts_with(p, "&radic;")) { sb_put_utf8(&out, 0x221A); p += 7; continue; }
            if (starts_with(p, "&pi;")) { sb_put_utf8(&out, 0x03C0); p += 4; continue; }
            if (p[1] == '#') {
                char *semi = strchr(p, ';');
                if (semi && semi - p < 10) {
                    long code = (p[2] == 'x' || p[2] == 'X') ? strtol(p + 3, NULL, 16)
                                                              : strtol(p + 2, NULL, 10);
                    sb_put_utf8(&out, code);
                    p = semi + 1;
                    continue;
                }
            }
        }
        sb_putc(&out, *p);
        p++;
    }
    free(in);
    return out.buf;
}

/* NetHackWiki's dungeon maps are marked up with a custom parser extension:
 *   <replacecharsblock rules="ttymap">
 *   G=[[Gnome_(monster)#Gnome|{{brown|G}}]]
 *   H=[[Gnome lord|{{blue|G}}]]
 *
 *    ---------------------------------
 *    |.%..|..|..%....%..|..|..|G.%...|
 *    ...
 *   </replacecharsblock>
 * The lines before the first blank line (or first line without a leading
 * "KEY=") are substitution rules: a single placeholder character (often a
 * non-ASCII one), '=', then the wikitext to substitute wherever that
 * character appears in the rest of the block. Splicing the rule's raw
 * wikitext in place (rather than resolving it here) lets it flow through
 * the normal template/link handling that follows this pass, so map glyphs
 * come out as the same colored, clickable links the legend itself uses --
 * instead of a raw, untranslated placeholder byte. */
static char *apply_replacecharsblock(char *in) {
    SB out; sb_init(&out);
    char *p = in;
    while (*p) {
        if (!starts_with_ci(p, "<replacecharsblock")) { sb_putc(&out, *p); p++; continue; }

        char *gt = strchr(p, '>');
        if (!gt) { sb_puts(&out, p); break; }
        for (char *q = p; q <= gt; q++) sb_putc(&out, *q);

        char *body_start = gt + 1;
        /* The opening tag is immediately followed by a newline ending its
         * own (otherwise-empty) line; consume it here so the rule-parsing
         * loop below sees the real first legend line first, rather than
         * mistaking that newline for the blank line that ends the legend. */
        while (*body_start == '\r' || *body_start == '\n') { sb_putc(&out, *body_start); body_start++; }

        char *close = find_ci(body_start, "</replacecharsblock>");
        char *body_end = close ? close : body_start + strlen(body_start);

        typedef struct { char key[32]; char *val; } Rule;
        Rule rules[128];
        int nrules = 0;

        char *lp = body_start;
        while (lp < body_end && nrules < 128) {
            char *nl = memchr(lp, '\n', (size_t)(body_end - lp));
            char *line_end = nl ? nl : body_end;
            size_t linelen = (size_t)(line_end - lp);
            if (linelen == 0) { lp = nl ? nl + 1 : body_end; break; }

            char *eq = memchr(lp, '=', linelen);
            size_t keylen = eq ? (size_t)(eq - lp) : 0;
            if (!eq || keylen == 0 || keylen > sizeof(rules[0].key) - 1) break;

            memcpy(rules[nrules].key, lp, keylen);
            rules[nrules].key[keylen] = '\0';
            size_t vallen = (size_t)(line_end - (eq + 1));
            rules[nrules].val = malloc(vallen + 1);
            memcpy(rules[nrules].val, eq + 1, vallen);
            rules[nrules].val[vallen] = '\0';
            nrules++;

            lp = nl ? nl + 1 : body_end;
        }

        /* Legend lines need the same verbatim, one-source-line-per-line
         * treatment as the map grid below them (mark_pre_blocks()'s
         * PRE_MARK, applied here since that pass runs later and knows
         * nothing about <replacecharsblock>). Without it they fall through
         * to ordinary paragraph parsing: consecutive lines get word-wrapped
         * and joined with spaces into a single run-on paragraph, and any
         * rule whose key happens to be a MediaWiki list marker at start of
         * line (e.g. "#=..." for a literal '#' glyph) gets misread as a
         * numbered list item instead of legend text. */
        int at_legend_line_start = 1;
        for (char *q = body_start; q < lp; q++) {
            if (at_legend_line_start) { sb_putc(&out, PRE_MARK); at_legend_line_start = 0; }
            sb_putc(&out, *q);
            if (*q == '\n') at_legend_line_start = 1;
        }

        /* Map lines don't necessarily follow MediaWiki's own leading-space
         * preformat convention -- this custom extension's whole point is
         * to be preformatted on its own via the surrounding <div>'s CSS,
         * so mark every line explicitly rather than relying on that. */
        int at_line_start = 1;
        for (char *mp = lp; mp < body_end; ) {
            if (at_line_start) { sb_putc(&out, PRE_MARK); at_line_start = 0; }
            if (*mp == '\n') { sb_putc(&out, '\n'); mp++; at_line_start = 1; continue; }
            /* Longest-match-first: legends can mix single-char keys (G, @)
             * with multi-char word keys (general, food) sharing a prefix. */
            int best_len = 0, best_idx = -1;
            for (int i = 0; i < nrules; i++) {
                size_t klen = strlen(rules[i].key);
                if (klen > 0 && (int)klen > best_len && (size_t)(body_end - mp) >= klen &&
                    memcmp(mp, rules[i].key, klen) == 0) {
                    best_len = (int)klen;
                    best_idx = i;
                }
            }
            if (best_idx >= 0) {
                sb_puts(&out, rules[best_idx].val);
                mp += best_len;
            } else {
                sb_putc(&out, *mp);
                mp++;
            }
        }

        for (int i = 0; i < nrules; i++) free(rules[i].val);
        p = body_end;
    }
    free(in);
    return out.buf;
}

static char *preprocess(const char *raw, const WikiIndex *idx) {
    char *s = malloc(strlen(raw) + 1);
    strcpy(s, raw);
    s = strip_comments(s);
    s = apply_replacecharsblock(s);
    s = strip_templates(s, idx, 0);
    s = strip_gallery(s);
    s = strip_refs(s);
    s = mark_pre_blocks(s);
    s = br_to_newline(s);
    s = strip_nowiki_markers(s);
    s = strip_generic_tags(s);
    s = decode_entities(s);
    return s;
}

/* ---------------- inline markup: bold/italic, links ---------------- */

static int is_image_keyword(const char *s) {
    static const char *kw[] = {
        "thumb", "thumbnail", "left", "right", "center", "centre", "none",
        "frame", "framed", "frameless", "border", "upright", NULL
    };
    for (int i = 0; kw[i]; i++) if (strcasecmp(s, kw[i]) == 0) return 1;
    size_t n = strlen(s);
    if (n > 2 && strcasecmp(s + n - 2, "px") == 0) return 1;
    if (strchr(s, '=')) return 1;
    return 0;
}

static void flush_buf(SB *buf, RunList *out, unsigned attr) {
    if (buf->len > 0) {
        runlist_push(out, buf->buf, attr, -1);
        buf->len = 0;
        buf->buf[0] = '\0';
    }
}

/* Finds the "]]" that matches the "[[" already consumed before `p`, so
 * captions containing their own nested [[links]] (common on image
 * captions) aren't cut off at the first, inner "]]". Returns a pointer to
 * the start of the matching "]]", or NULL if unterminated. */
static const char *find_link_close(const char *p) {
    int depth = 1;
    while (*p) {
        if (p[0] == '[' && p[1] == '[') { depth++; p += 2; continue; }
        if (p[0] == ']' && p[1] == ']') {
            depth--;
            if (depth == 0) return p;
            p += 2;
            continue;
        }
        p++;
    }
    return NULL;
}

/* Splits `s` on top-level '|' characters, ignoring ones nested inside
 * [[ ... ]] (image captions routinely contain their own [[links]]).
 * Returns a malloc'd array of malloc'd strings; caller frees both. */
static char **depth_split_pipe(const char *s, int *out_n) {
    int cap = 8, n = 0;
    char **out = malloc(cap * sizeof(char *));
    int depth = 0;
    const char *seg = s;
    const char *p = s;
    while (*p) {
        if (p[0] == '[' && p[1] == '[') { depth++; p += 2; continue; }
        if (p[0] == ']' && p[1] == ']') { if (depth > 0) depth--; p += 2; continue; }
        if (depth == 0 && *p == '|') {
            size_t len = (size_t)(p - seg);
            char *piece = malloc(len + 1);
            memcpy(piece, seg, len);
            piece[len] = '\0';
            if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
            out[n++] = piece;
            p++;
            seg = p;
            continue;
        }
        p++;
    }
    size_t len = (size_t)(p - seg);
    char *piece = malloc(len + 1);
    memcpy(piece, seg, len);
    piece[len] = '\0';
    if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
    out[n++] = piece;
    *out_n = n;
    return out;
}

static void inline_parse(const char *text, Doc *doc, const WikiIndex *idx, RunList *out, int *bold, int *italic);

static const char *handle_internal_link(const char *p, Doc *doc, const WikiIndex *idx, RunList *out) {
    p += 2; /* skip [[ */
    const char *end = find_link_close(p);
    const char *stop = end ? end : p + strlen(p);
    size_t clen = (size_t)(stop - p);
    char content[2048];
    size_t cl = clen < sizeof(content) - 1 ? clen : sizeof(content) - 1;
    memcpy(content, p, cl);
    content[cl] = '\0';
    const char *after = end ? end + 2 : stop;

    char *pipe = strchr(content, '|');
    char target_buf[1024];
    if (pipe) {
        size_t tl = (size_t)(pipe - content);
        if (tl > sizeof(target_buf) - 1) tl = sizeof(target_buf) - 1;
        memcpy(target_buf, content, tl);
        target_buf[tl] = '\0';
    } else {
        strncpy(target_buf, content, sizeof(target_buf) - 1);
        target_buf[sizeof(target_buf) - 1] = '\0';
    }
    trim_inplace(target_buf);

    if (starts_with_ci(target_buf, "Category:")) {
        return after; /* categories aren't shown inline, matching MediaWiki */
    }

    if (starts_with_ci(target_buf, "File:") || starts_with_ci(target_buf, "Image:")) {
        int np;
        char **params = depth_split_pipe(content, &np); /* params[0] = filename */
        char *caption = NULL;
        for (int i = np - 1; i >= 1; i--) {
            char t[512];
            strncpy(t, params[i], sizeof(t) - 1);
            t[sizeof(t) - 1] = '\0';
            trim_inplace(t);
            if (t[0] && !is_image_keyword(t)) { caption = params[i]; break; }
        }
        if (caption) {
            trim_inplace(caption);
            runlist_push(out, "[Image: ", ATTR_DIM, -1);
            int bold = 0, italic = 0;
            inline_parse(caption, doc, idx, out, &bold, &italic);
            runlist_push(out, "]", ATTR_DIM, -1);
        } else {
            runlist_push(out, "[Image]", ATTR_DIM, -1);
        }
        for (int i = 0; i < np; i++) free(params[i]);
        free(params);
        return after;
    }

    char display_buf[1024];
    if (pipe) {
        strncpy(display_buf, pipe + 1, sizeof(display_buf) - 1);
        display_buf[sizeof(display_buf) - 1] = '\0';
        trim_inplace(display_buf);
    } else {
        strncpy(display_buf, target_buf, sizeof(display_buf) - 1);
        display_buf[sizeof(display_buf) - 1] = '\0';
        for (char *c = display_buf; *c; c++) if (*c == '_') *c = ' ';
        char *hash = strchr(display_buf, '#');
        if (hash) *hash = '\0';
        trim_inplace(display_buf);
    }
    if (!display_buf[0]) {
        strncpy(display_buf, target_buf, sizeof(display_buf) - 1);
        display_buf[sizeof(display_buf) - 1] = '\0';
    }

    int found = wiki_index_resolve(idx, target_buf);
    const char *resolved_title = found >= 0 ? idx->articles[found].title : target_buf;
    int link_idx = doc_add_link(doc, display_buf, resolved_title, found >= 0, found);
    runlist_push(out, display_buf, 0, link_idx);
    return after;
}

/* Single-bracket external links, e.g. [http://... label]. Never made
 * navigable -- this app does no networking, so these are always inert
 * text, shown dimmed to signal they're not clickable. */
static const char *handle_external_link(const char *p, RunList *out) {
    p += 1; /* skip [ */
    const char *end = strchr(p, ']');
    const char *stop = end ? end : p + strlen(p);
    size_t clen = (size_t)(stop - p);
    char content[1024];
    size_t cl = clen < sizeof(content) - 1 ? clen : sizeof(content) - 1;
    memcpy(content, p, cl);
    content[cl] = '\0';
    const char *after = end ? end + 1 : stop;

    if (starts_with_ci(content, "http://") || starts_with_ci(content, "https://") ||
        starts_with_ci(content, "ftp://") || starts_with_ci(content, "mailto:")) {
        char *sp = content;
        while (*sp && !isspace((unsigned char)*sp)) sp++;
        char label[900];
        if (*sp) {
            while (isspace((unsigned char)*sp)) sp++;
            strncpy(label, sp, sizeof(label) - 1);
        } else {
            strncpy(label, content, sizeof(label) - 1);
        }
        label[sizeof(label) - 1] = '\0';
        trim_inplace(label);
        if (!label[0]) { strncpy(label, content, sizeof(label) - 1); label[sizeof(label) - 1] = '\0'; }
        runlist_push(out, label, ATTR_DIM, -1);
    } else {
        char lit[1050];
        snprintf(lit, sizeof(lit), "[%s]", content);
        runlist_push(out, lit, 0, -1);
    }
    return after;
}

static void inline_parse(const char *text, Doc *doc, const WikiIndex *idx, RunList *out, int *bold, int *italic) {
    SB buf; sb_init(&buf);
    const char *p = text;
    while (*p) {
        unsigned attr = (unsigned)((*bold ? ATTR_BOLD : 0) | (*italic ? ATTR_ITALIC : 0));

        if (p[0] == '\'' && p[1] == '\'') {
            int run = 0;
            const char *q = p;
            while (*q == '\'') { run++; q++; }
            flush_buf(&buf, out, attr);
            if (run == 2) {
                *italic = !*italic;
            } else if (run == 3) {
                *bold = !*bold;
            } else if (run == 4) {
                runlist_push(out, "'", attr, -1);
                *bold = !*bold;
            } else { /* run >= 5 */
                *bold = !*bold;
                *italic = !*italic;
                for (int i = 0; i < run - 5; i++) sb_putc(&buf, '\'');
            }
            p = q;
            continue;
        }
        if (p[0] == '[' && p[1] == '[') {
            flush_buf(&buf, out, attr);
            p = handle_internal_link(p, doc, idx, out);
            continue;
        }
        if (p[0] == '[') {
            flush_buf(&buf, out, attr);
            p = handle_external_link(p, out);
            continue;
        }
        if (starts_with_ci(p, "http://") || starts_with_ci(p, "https://")) {
            flush_buf(&buf, out, attr);
            const char *q = p;
            while (*q && !isspace((unsigned char)*q)) q++;
            char url[1024];
            size_t ul = (size_t)(q - p);
            if (ul > sizeof(url) - 1) ul = sizeof(url) - 1;
            memcpy(url, p, ul);
            url[ul] = '\0';
            runlist_push(out, url, ATTR_DIM, -1);
            p = q;
            continue;
        }

        sb_putc(&buf, *p);
        p++;
    }
    unsigned attr = (unsigned)((*bold ? ATTR_BOLD : 0) | (*italic ? ATTR_ITALIC : 0));
    flush_buf(&buf, out, attr);
    free(buf.buf);
}

/* ---------------- block-level parsing ---------------- */

static int parse_heading(Doc *doc, const char *ls, const WikiIndex *idx) {
    size_t len = strlen(ls);
    size_t end = len;
    while (end > 0 && isspace((unsigned char)ls[end - 1])) end--;
    int lead = 0;
    while (lead < (int)end && ls[lead] == '=') lead++;
    if (lead < 1) return 0;
    int trail = 0;
    while (trail < (int)end - lead && ls[end - 1 - trail] == '=') trail++;
    if (trail < 1) return 0;
    int level = lead < trail ? lead : trail;
    if (level < 1) return 0;
    if (level > 6) level = 6;
    int inner_start = lead;
    int inner_end = (int)end - trail;
    if (inner_end <= inner_start) return 0;

    char inner[2048];
    int il = inner_end - inner_start;
    if (il > (int)sizeof(inner) - 1) il = (int)sizeof(inner) - 1;
    memcpy(inner, ls + inner_start, il);
    inner[il] = '\0';
    trim_inplace(inner);
    if (!inner[0]) return 0;

    Block *b = doc_add_block(doc, BLK_HEADING);
    b->level = level;
    int bold = 0, italic = 0;
    inline_parse(inner, doc, idx, &b->text, &bold, &italic);
    return level;
}

static void parse_list_item(Doc *doc, const char *ls, const WikiIndex *idx) {
    int level = 0, ordered = 0;
    const char *p = ls;
    while (*p == '*' || *p == '#' || *p == ':' || *p == ';') {
        if (*p == '#') ordered = 1;
        level++;
        p++;
    }
    while (*p == ' ') p++;

    Block *b = doc_add_block(doc, BLK_LIST_ITEM);
    b->level = level;
    b->ordered = ordered;
    int bold = 0, italic = 0;
    inline_parse(p, doc, idx, &b->text, &bold, &italic);
}

/* Splits `s` on a 2-char delimiter (e.g. "||" or "!!"), ignoring occurrences
 * inside [[ ... ]] spans. Returns a malloc'd array of malloc'd, trimmed
 * strings; caller frees each string and the array. */
static char **depth_split(const char *s, const char *delim2, int *out_n) {
    int cap = 8, n = 0;
    char **out = malloc(cap * sizeof(char *));
    int depth = 0;
    const char *start = s;
    const char *p = s;
    while (*p) {
        if (p[0] == '[' && p[1] == '[') { depth++; p += 2; continue; }
        if (p[0] == ']' && p[1] == ']') { if (depth > 0) depth--; p += 2; continue; }
        if (depth == 0 && p[0] == delim2[0] && p[1] == delim2[1]) {
            size_t len = (size_t)(p - start);
            char *piece = malloc(len + 1);
            memcpy(piece, start, len);
            piece[len] = '\0';
            trim_inplace(piece);
            if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
            out[n++] = piece;
            p += 2;
            start = p;
            continue;
        }
        p++;
    }
    size_t len = (size_t)(p - start);
    char *piece = malloc(len + 1);
    memcpy(piece, start, len);
    piece[len] = '\0';
    trim_inplace(piece);
    if (n == cap) { cap *= 2; out = realloc(out, cap * sizeof(char *)); }
    out[n++] = piece;
    *out_n = n;
    return out;
}

/* Finds the first top-level '|' in a table cell/caption's raw content,
 * skipping any '|' nested inside a [[link|display]] span -- same
 * depth-tracking approach as depth_split(), just for a single delimiter
 * instead of a whole-line split. Cells and `|+` captions both use this to
 * split an optional "attrs | content" prefix from the real content, e.g.:
 *   rowspan="2" | Artifact name
 *   |+ class="nowrap" | '''Attributed caption'''
 * A piece with no top-level pipe at all has no attributes -- it's already
 * just the content. */
static const char *find_toplevel_pipe(const char *s) {
    int depth = 0;
    for (const char *p = s; *p; p++) {
        if (p[0] == '[' && p[1] == '[') { depth++; p++; continue; }
        if (p[0] == ']' && p[1] == ']') { if (depth > 0) depth--; p++; continue; }
        if (depth == 0 && *p == '|') return p;
    }
    return NULL;
}

static void table_row_add_cells(Block *row, const char *content, const char *delim2, Doc *doc, const WikiIndex *idx) {
    int n;
    char **cells = depth_split(content, delim2, &n);
    for (int c = 0; c < n; c++) {
        /* A cell can carry HTML-style attributes before its content,
         * separated by one more top-level '|', e.g.
         * `rowspan="2" | Artifact name` or `class="unsortable" | Carried`
         * (find_toplevel_pipe() is the same helper |+ table captions
         * already use for this exact "attrs | content" split, just
         * applied per-cell here instead of once for the whole caption
         * line). Most cells have no attributes at all -- no top-level
         * pipe means the whole piece is already just the content. */
        const char *cell_text = cells[c];
        const char *pipe = find_toplevel_pipe(cell_text);
        if (pipe) {
            cell_text = pipe + 1;
            while (*cell_text == ' ' || *cell_text == '\t') cell_text++;
        }
        row->cells = realloc(row->cells, (row->n_cells + 1) * sizeof(RunList));
        memset(&row->cells[row->n_cells], 0, sizeof(RunList));
        int bold = 0, italic = 0;
        inline_parse(cell_text, doc, idx, &row->cells[row->n_cells], &bold, &italic);
        row->n_cells++;
        free(cells[c]);
    }
    free(cells);
}

/* Parses a {| ... |} table starting at lines[li] (the "{|" line) through
 * the matching "|}" (or EOF). Returns the index of the line after the
 * table. */
static int parse_table_block(Doc *doc, char **lines, int n_lines, int li, const WikiIndex *idx) {
    li++;
    Block *cur_row = NULL;

    while (li < n_lines) {
        char *line = lines[li];
        char *ls = line;
        while (*ls == ' ' || *ls == '\t') ls++;

        if (starts_with(ls, "|}")) { li++; break; }
        if (starts_with(ls, "|-")) { cur_row = NULL; li++; continue; }
        if (starts_with(ls, "|+")) {
            const char *rest = ls + 2;
            const char *pipe = find_toplevel_pipe(rest);
            const char *cap = pipe ? pipe + 1 : rest;
            char capbuf[2048];
            strncpy(capbuf, cap, sizeof(capbuf) - 1);
            capbuf[sizeof(capbuf) - 1] = '\0';
            trim_inplace(capbuf);
            if (capbuf[0]) {
                Block *capb = doc_add_block(doc, BLK_TABLE_CAPTION);
                int bold = 0, italic = 0;
                inline_parse(capbuf, doc, idx, &capb->text, &bold, &italic);
            }
            li++;
            continue;
        }

        if (ls[0] == '!') {
            if (!cur_row) cur_row = doc_add_block(doc, BLK_TABLE_ROW);
            cur_row->header_row = 1;
            table_row_add_cells(cur_row, ls + 1, "!!", doc, idx);
            li++;
            continue;
        }
        if (ls[0] == '|') {
            if (!cur_row) cur_row = doc_add_block(doc, BLK_TABLE_ROW);
            table_row_add_cells(cur_row, ls + 1, "||", doc, idx);
            li++;
            continue;
        }
        li++; /* stray line (e.g. table-tag attributes on their own line) */
    }
    return li;
}

static char **split_lines(char *text, int *out_n) {
    int cap = 256, n = 0;
    char **lines = malloc(cap * sizeof(char *));
    lines[n++] = text;
    for (char *c = text; *c; c++) {
        if (*c == '\n') {
            *c = '\0';
            if (n == cap) { cap *= 2; lines = realloc(lines, cap * sizeof(char *)); }
            lines[n++] = c + 1;
        }
    }
    *out_n = n;
    return lines;
}

Doc *wikitext_parse(const char *title, const char *raw, const WikiIndex *idx) {
    Doc *doc = doc_new(title);
    char *text = preprocess(raw, idx);

    int n_lines;
    char **lines = split_lines(text, &n_lines);
    for (int i = 0; i < n_lines; i++) {
        size_t l = strlen(lines[i]);
        while (l > 0 && lines[i][l - 1] == '\r') lines[i][--l] = '\0';
    }

    Block *open_para = NULL;
    int para_bold = 0, para_italic = 0;

    int li = 0;
    while (li < n_lines) {
        char *line = lines[li];

        /* Preformatted line: MediaWiki's leading-space convention, or a
         * line marked by mark_pre_blocks() as having been inside <pre>.
         * Rendered verbatim (see BLK_PRE in doc_wrap) -- never word-wrapped
         * or joined with neighboring lines, which is what NetHackWiki's
         * ASCII dungeon maps rely on for their layout. */
        if (line[0] == ' ' || line[0] == PRE_MARK) {
            open_para = NULL;
            Block *pre = doc_add_block(doc, BLK_PRE);
            while (li < n_lines && (lines[li][0] == ' ' || lines[li][0] == PRE_MARK)) {
                pre->cells = realloc(pre->cells, (size_t)(pre->n_cells + 1) * sizeof(RunList));
                memset(&pre->cells[pre->n_cells], 0, sizeof(RunList));
                int bold = 0, italic = 0;
                inline_parse(lines[li] + 1, doc, idx, &pre->cells[pre->n_cells], &bold, &italic);
                pre->n_cells++;
                li++;
            }
            continue;
        }

        char *ls = line;
        while (*ls == ' ' || *ls == '\t') ls++;

        if (*ls == '\0') {
            open_para = NULL;
            if (doc->n_blocks > 0 && doc->blocks[doc->n_blocks - 1].type != BLK_BLANK)
                doc_add_block(doc, BLK_BLANK);
            li++;
            continue;
        }
        if (starts_with(ls, "{|")) {
            open_para = NULL;
            li = parse_table_block(doc, lines, n_lines, li, idx);
            continue;
        }
        if (ls[0] == '=') {
            open_para = NULL;
            int lvl = parse_heading(doc, ls, idx);
            if (lvl > 0) { li++; continue; }
            /* not a real heading; fall through and treat as paragraph text */
        }
        if (starts_with(ls, "----")) {
            open_para = NULL;
            doc_add_block(doc, BLK_HR);
            li++;
            continue;
        }
        if (ls[0] == '*' || ls[0] == '#' || ls[0] == ':' || ls[0] == ';') {
            open_para = NULL;
            parse_list_item(doc, ls, idx);
            li++;
            continue;
        }

        if (!open_para) {
            open_para = doc_add_block(doc, BLK_PARAGRAPH);
            para_bold = 0;
            para_italic = 0;
        } else {
            runlist_push(&open_para->text, " ", 0, -1);
        }
        inline_parse(ls, doc, idx, &open_para->text, &para_bold, &para_italic);
        li++;
    }

    free(lines);
    free(text);
    return doc;
}
